// Core 50 MHz AXI128 and host 250 MHz PCIS AXI512 share a bounded DDR aperture.
module coral_ddr_subsystem #(
    parameter integer TIMEOUT_CYCLES = 1048576
) (
    input wire core_clk,
    core_rst_n,
    host_clk,
    host_rst_n,
    ddr_ready,
    output wire ddr_fault,
    input wire [31:0] c_awaddr,
    input wire [5:0] c_awid,
    input wire [7:0] c_awlen,
    input wire [2:0] c_awsize,
    input wire [1:0] c_awburst,
    input wire c_awlock,
    input wire c_awvalid,
    output wire c_awready,
    input wire [127:0] c_wdata,
    input wire [15:0] c_wstrb,
    input wire c_wlast,
    input wire c_wvalid,
    output wire c_wready,
    output wire [5:0] c_bid,
    output wire [1:0] c_bresp,
    output wire c_bvalid,
    input wire c_bready,
    input wire [31:0] c_araddr,
    input wire [5:0] c_arid,
    input wire [7:0] c_arlen,
    input wire [2:0] c_arsize,
    input wire [1:0] c_arburst,
    input wire c_arlock,
    input wire c_arvalid,
    output wire c_arready,
    output wire [127:0] c_rdata,
    output wire [5:0] c_rid,
    output wire [1:0] c_rresp,
    output wire c_rlast,
    output wire c_rvalid,
    input wire c_rready,
    input wire [63:0] h_awaddr,
    input wire [15:0] h_awid,
    input wire [7:0] h_awlen,
    input wire [2:0] h_awsize,
    input wire [1:0] h_awburst,
    input wire h_awlock,
    input wire h_awvalid,
    output wire h_awready,
    input wire [511:0] h_wdata,
    input wire [63:0] h_wstrb,
    input wire h_wlast,
    input wire h_wvalid,
    output wire h_wready,
    output wire [15:0] h_bid,
    output wire [1:0] h_bresp,
    output wire h_bvalid,
    input wire h_bready,
    input wire [63:0] h_araddr,
    input wire [15:0] h_arid,
    input wire [7:0] h_arlen,
    input wire [2:0] h_arsize,
    input wire [1:0] h_arburst,
    input wire h_arlock,
    input wire h_arvalid,
    output wire h_arready,
    output wire [511:0] h_rdata,
    output wire [15:0] h_rid,
    output wire [1:0] h_rresp,
    output wire h_rlast,
    output wire h_rvalid,
    input wire h_rready,
    output wire [63:0] m_awaddr,
    output wire [15:0] m_awid,
    output wire [7:0] m_awlen,
    output wire [2:0] m_awsize,
    output wire [1:0] m_awburst,
    output wire m_awvalid,
    input wire m_awready,
    output wire [511:0] m_wdata,
    output wire [63:0] m_wstrb,
    output wire m_wlast,
    output wire m_wvalid,
    input wire m_wready,
    input wire [15:0] m_bid,
    input wire [1:0] m_bresp,
    input wire m_bvalid,
    output wire m_bready,
    output wire [63:0] m_araddr,
    output wire [15:0] m_arid,
    output wire [7:0] m_arlen,
    output wire [2:0] m_arsize,
    output wire [1:0] m_arburst,
    output wire m_arvalid,
    input wire m_arready,
    input wire [511:0] m_rdata,
    input wire [15:0] m_rid,
    input wire [1:0] m_rresp,
    input wire m_rlast,
    input wire m_rvalid,
    output wire m_rready
);
  wire [1:0] req_valid, req_ready, req_write, rsp_valid, rsp_ready;
  wire [1:0][31:0] req_addr;
  wire [1:0][511:0] req_wdata;
  wire [1:0][63:0] req_wstrb;
  wire [511:0] rsp_rdata;
  wire [1:0] rsp_resp;
  wire c_req_valid, c_req_ready, c_req_write, c_rsp_valid, c_rsp_ready;
  wire [31:0] c_req_addr;
  wire [511:0] c_req_wdata, c_rsp_rdata;
  wire [63:0] c_req_wstrb;
  wire [ 1:0] c_rsp_resp;
  coral_ddr_frontend #(
      .DATA_WIDTH(128),
      .ADDR_WIDTH(32),
      .ID_WIDTH  (6),
      .BASE_ADDR (64'h20000000)
  ) i_c_frontend (
      .clk(core_clk),
      .rst_n(core_rst_n),
      .s_awaddr(c_awaddr),
      .s_awid(c_awid),
      .s_awlen(c_awlen),
      .s_awsize(c_awsize),
      .s_awburst(c_awburst),
      .s_awlock(c_awlock),
      .s_awvalid(c_awvalid),
      .s_awready(c_awready),
      .s_wdata(c_wdata),
      .s_wstrb(c_wstrb),
      .s_wlast(c_wlast),
      .s_wvalid(c_wvalid),
      .s_wready(c_wready),
      .s_bid(c_bid),
      .s_bresp(c_bresp),
      .s_bvalid(c_bvalid),
      .s_bready(c_bready),
      .s_araddr(c_araddr),
      .s_arid(c_arid),
      .s_arlen(c_arlen),
      .s_arsize(c_arsize),
      .s_arburst(c_arburst),
      .s_arlock(c_arlock),
      .s_arvalid(c_arvalid),
      .s_arready(c_arready),
      .s_rdata(c_rdata),
      .s_rid(c_rid),
      .s_rresp(c_rresp),
      .s_rlast(c_rlast),
      .s_rvalid(c_rvalid),
      .s_rready(c_rready),
      .req_valid(c_req_valid),
      .req_ready(c_req_ready),
      .req_write(c_req_write),
      .req_addr(c_req_addr),
      .req_wdata(c_req_wdata),
      .req_wstrb(c_req_wstrb),
      .rsp_valid(c_rsp_valid),
      .rsp_ready(c_rsp_ready),
      .rsp_rdata(c_rsp_rdata),
      .rsp_resp(c_rsp_resp)
  );
  coral_ddr_frontend #(
      .DATA_WIDTH(512),
      .ADDR_WIDTH(64),
      .ID_WIDTH  (16),
      .BASE_ADDR (64'h0)
  ) i_h_frontend (
      .clk(host_clk),
      .rst_n(host_rst_n),
      .s_awaddr(h_awaddr),
      .s_awid(h_awid),
      .s_awlen(h_awlen),
      .s_awsize(h_awsize),
      .s_awburst(h_awburst),
      .s_awlock(h_awlock),
      .s_awvalid(h_awvalid),
      .s_awready(h_awready),
      .s_wdata(h_wdata),
      .s_wstrb(h_wstrb),
      .s_wlast(h_wlast),
      .s_wvalid(h_wvalid),
      .s_wready(h_wready),
      .s_bid(h_bid),
      .s_bresp(h_bresp),
      .s_bvalid(h_bvalid),
      .s_bready(h_bready),
      .s_araddr(h_araddr),
      .s_arid(h_arid),
      .s_arlen(h_arlen),
      .s_arsize(h_arsize),
      .s_arburst(h_arburst),
      .s_arlock(h_arlock),
      .s_arvalid(h_arvalid),
      .s_arready(h_arready),
      .s_rdata(h_rdata),
      .s_rid(h_rid),
      .s_rresp(h_rresp),
      .s_rlast(h_rlast),
      .s_rvalid(h_rvalid),
      .s_rready(h_rready),
      .req_valid(req_valid[1]),
      .req_ready(req_ready[1]),
      .req_write(req_write[1]),
      .req_addr(req_addr[1]),
      .req_wdata(req_wdata[1]),
      .req_wstrb(req_wstrb[1]),
      .rsp_valid(rsp_valid[1]),
      .rsp_ready(rsp_ready[1]),
      .rsp_rdata(rsp_rdata),
      .rsp_resp(rsp_resp)
  );
  coral_ddr_cdc i_core_cdc (
      .s_clk(core_clk),
      .s_rst_n(core_rst_n),
      .m_clk(host_clk),
      .m_rst_n(host_rst_n),
      .s_req_valid(c_req_valid),
      .m_req_valid(req_valid[0]),
      .s_req_ready(c_req_ready),
      .m_req_ready(req_ready[0]),
      .s_req_write(c_req_write),
      .m_req_write(req_write[0]),
      .s_req_addr(c_req_addr),
      .m_req_addr(req_addr[0]),
      .s_req_wdata(c_req_wdata),
      .m_req_wdata(req_wdata[0]),
      .s_req_wstrb(c_req_wstrb),
      .m_req_wstrb(req_wstrb[0]),
      .s_rsp_valid(c_rsp_valid),
      .m_rsp_valid(rsp_valid[0]),
      .s_rsp_ready(c_rsp_ready),
      .m_rsp_ready(rsp_ready[0]),
      .s_rsp_rdata(c_rsp_rdata),
      .m_rsp_rdata(rsp_rdata),
      .s_rsp_resp(c_rsp_resp),
      .m_rsp_resp(rsp_resp)
  );
  coral_ddr_backend #(
      .TIMEOUT_CYCLES(TIMEOUT_CYCLES)
  ) i_backend (
      .clk(host_clk),
      .rst_n(host_rst_n),
      .ddr_ready(ddr_ready),
      .fault(ddr_fault),
      .req_valid(req_valid),
      .req_ready(req_ready),
      .req_write(req_write),
      .req_addr(req_addr),
      .req_wdata(req_wdata),
      .req_wstrb(req_wstrb),
      .rsp_valid(rsp_valid),
      .rsp_ready(rsp_ready),
      .rsp_rdata(rsp_rdata),
      .rsp_resp(rsp_resp),
      .m_awaddr(m_awaddr),
      .m_awid(m_awid),
      .m_awlen(m_awlen),
      .m_awsize(m_awsize),
      .m_awburst(m_awburst),
      .m_awvalid(m_awvalid),
      .m_awready(m_awready),
      .m_wdata(m_wdata),
      .m_wstrb(m_wstrb),
      .m_wlast(m_wlast),
      .m_wvalid(m_wvalid),
      .m_wready(m_wready),
      .m_bid(m_bid),
      .m_bresp(m_bresp),
      .m_bvalid(m_bvalid),
      .m_bready(m_bready),
      .m_araddr(m_araddr),
      .m_arid(m_arid),
      .m_arlen(m_arlen),
      .m_arsize(m_arsize),
      .m_arburst(m_arburst),
      .m_arvalid(m_arvalid),
      .m_arready(m_arready),
      .m_rdata(m_rdata),
      .m_rid(m_rid),
      .m_rresp(m_rresp),
      .m_rlast(m_rlast),
      .m_rvalid(m_rvalid),
      .m_rready(m_rready)
  );
endmodule
